In [1]:
import pandas as pd
import numpy as np

model_df = pd.read_csv(
    "../data/processed/neighbourhood_demand.csv"
)

model_df["datetime"] = pd.to_datetime(
    model_df["datetime"]
)

model_df = model_df[
    model_df["datetime"] >= "2013-01-01"
].copy()

model_df.head()

                 datetime  total_demand_kwh
19420 2013-01-01 00:00:00           220.013
19421 2013-01-01 00:30:00           204.270
19422 2013-01-01 01:00:00           189.439
19423 2013-01-01 01:30:00           173.019
19424 2013-01-01 02:00:00           154.537

In [2]:
model_df["hour"] = model_df["datetime"].dt.hour

model_df["day"] = model_df["datetime"].dt.day

model_df["month"] = model_df["datetime"].dt.month

model_df["weekday"] = model_df["datetime"].dt.weekday

model_df["is_weekend"] = (
    model_df["weekday"].isin([5,6])
).astype(int)

In [3]:
model_df.head()

,datetime,total_demand_kwh,hour,day,month,weekday,is_weekend
19420,2013-01-01 00:00:00,220.013,0,1,1,1,0
19421,2013-01-01 00:30:00,204.270,0,1,1,1,0
19422,2013-01-01 01:00:00,189.439,1,1,1,1,0
19423,2013-01-01 01:30:00,173.019,1,1,1,1,0
19424,2013-01-01 02:00:00,154.537,2,1,1,1,0

In [4]:
def get_season(month):

    if month in [12,1,2]:
        return 0      # Winter

    elif month in [3,4,5]:
        return 1      # Spring

    elif month in [6,7,8]:
        return 2      # Summer

    else:
        return 3      # Autumn

model_df["season"] = (
    model_df["month"]
    .apply(get_season)
)

In [5]:
model_df["lag_1"] = (
    model_df["total_demand_kwh"]
    .shift(1)
)

In [6]:
model_df["lag_48"] = (
    model_df["total_demand_kwh"]
    .shift(48)
)

In [7]:
model_df["lag_96"] = (
    model_df["total_demand_kwh"]
    .shift(96)
)

In [8]:
model_df["rolling_mean_48"] = (
    model_df["total_demand_kwh"]
    .rolling(48)
    .mean()
)

In [9]:
model_df["rolling_std_48"] = (
    model_df["total_demand_kwh"]
    .rolling(48)
    .std()
)

In [10]:
model_df.isnull().sum()

datetime             0
total_demand_kwh     0
hour                 0
day                  0
month                0
weekday              0
is_weekend           0
season               0
lag_1                1
lag_48              48
lag_96              96
rolling_mean_48     47
rolling_std_48      47
dtype: int64

In [11]:
model_df = model_df.dropna()

In [12]:
model_df.isnull().sum()

datetime            0
total_demand_kwh    0
hour                0
day                 0
month               0
weekday             0
is_weekend          0
season              0
lag_1               0
lag_48              0
lag_96              0
rolling_mean_48     0
rolling_std_48      0
dtype: int64

In [13]:
print(model_df.shape)

(20209, 13)

In [14]:
model_df.head()

,datetime,total_demand_kwh,hour,day,month,weekday,is_weekend,season,lag_1,lag_48,lag_96,rolling_mean_48,rolling_std_48
19516,2013-01-03 00:00:00,209.864,0,3,1,3,0,0,243.522,198.338,220.013,240.736854,91.920733
19517,2013-01-03 00:30:00,175.020,0,3,1,3,0,0,209.864,165.862,204.270,240.927646,91.771399
19518,2013-01-03 01:00:00,151.394,1,3,1,3,0,0,175.020,147.971,189.439,240.998958,91.698930
19519,2013-01-03 01:30:00,137.672,1,3,1,3,0,0,151.394,129.889,173.019,241.161104,91.504956
19520,2013-01-03 02:00:00,128.217,2,3,1,3,0,0,137.672,117.542,154.537,241.383500,91.210616

In [15]:
model_df.to_csv(
    "../data/processed/model_ready_data.csv",
    index=False
)

NameError: name 'model_df' is not defined